### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by rodo2268** [swarm-lab/Rvision#45] opened 2022-02-16 22:20 UTC
Hi! I noticed Rvision was not working so I eliminated it and trief to reinstall it. However, at the end of the installation I get this:

ERROR: compilation failed for package 'Rvision'
* removing 'C:/Users/erodofili/Documents/R/win-library/4.1/Rvision'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/ERODOF~1/AppData/Local/Temp/Rtmpmad8nD/file33e874a1407b/Rvision_0.6.0.tar.gz’ had non-zero exit status

And the installation does not seem to complete. How can I solve this? Thanks!

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**
 - Operating system: [e.g. MacOS]
 - Version [e.g. 11.2.1]

**R (please complete the following information):**
 - R version: [e.g. 4.0.4]
 - Rvision version: [e.g. 0.4.2]
 - ROpenCVLite version: [e.g. 4.50.0]

**Additional context**

**Comment by sjmgarnier** [comment] 2022-02-16 22:33
@rodo2268 I suggest the following: 

- Update ROpenCVLite to its latest version (4.52.0)
- After the update, recompile OpenCV with `ROpenCVLite::installOpenCV()`
- Install the latest version of Rvision (0.6.0) with `remotes::install_github("swarm-lab/Rvision")`

If the problem persists, post here the full output of the installation process.

**Comment by rodo2268** [comment] 2022-02-16 22:55
Actually, that led to the following error in the ROpenCVLite installation when I tried to reinstall

Error: package or namespace load failed for ‘ROpenCVLite’:
 .onAttach failed in attachNamespace() for 'ROpenCVLite', details:
  call: system(command, as.integer(flag), f, stdout, stderr, timeout)
  error: character string expected as first argument

**Comment by sjmgarnier** [comment] 2022-02-16 23:04
@rodo2268 Ok, thanks. Someone else reported that error here: https://github.com/swarm-lab/ROpenCVLite/issues/24. I will investigate the problem as soon as I can (and as soon as I can put my hands on a Windows machine).

**Comment by sjmgarnier** [comment] 2022-02-17 02:17
@rodo2268 This last error should be fixed by 802f804d19b9e181b157a730d1abed2ebe4f3909. It was an error caused by a new behavior in `pkgbuild`. I will push the change in `ROpenCVLite` to CRAN asap, but you can install the update from Github now.

**Comment by rodo2268** [comment] 2022-02-17 04:48
@sjmgarnier thanks for all your help. It works now

**Closed** 2022-02-17 11:54 UTC
